from .base import BasePainter

class EasyGamePainter(BasePainter):

    def draw_current_state(self, numFails):
        if numFails == 0:
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
        elif numFails == 1:
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('.|.......|.')
        elif numFails == 2:
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('._________.')
            print('.|.......|.')
        elif numFails == 3:
            print('...........')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 4:
            print('.---------.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 5:
            print('.---------.')
            print('.......\\.|.')
            print('........\\|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 6:
            print('.---------.')
            print('.......\\.|.')
            print('....O...\\|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 7:
            print('.---------.')
            print('.......\\.|.')
            print('....O...\\|.')
            print('....|....|.')
            print('....|....|.')
            print('.........|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 8:
            print('.---------.')
            print('.......\\.|.')
            print('....O...\\|.')
            print('....|/...|.')
            print('....|....|.')
            print('.........|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 9:
            print('.---------.')
            print('.......\\.|.')
            print('....O...\\|.')
            print('...\\|/...|.')
            print('....|....|.')
            print('.........|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 10:
            print('.---------.')
            print('.......\\.|.')
            print('....O...\\|.')
            print('...\\|/...|.')
            print('....|....|.')
            print('.....\\...|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        elif numFails == 11:
            print('.---------.')
            print('.......\\.|.')
            print('....O...\\|.')
            print('...\\|/...|.')
            print('....|....|.')
            print('.../.\\...|.')
            print('.........|.')
            print('._________.')
            print('.|.......|.')
        print()
