from .base import BasePainter

class HardGamePainter(BasePainter):

    def draw_current_state(self, numFails):
        if numFails == 0:
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
        elif numFails == 1:
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('...........')
            print('._________.')
            print('.|.......|.')
        elif numFails == 2:
            print('..-------..')
            print('......\\.|..')
            print('.......\\|..')
            print('........|..')
            print('........|..')
            print('........|..')
            print('........|..')
            print('._________.')
            print('.|.......|.')
        elif numFails == 3:
            print('..-------..')
            print('......\\.|..')
            print('....O..\\|..')
            print('....|...|..')
            print('....|...|..')
            print('........|..')
            print('........|..')
            print('._________.')
            print('.|.......|.')
        elif numFails == 4:
            print('..-------..')
            print('......\\.|..')
            print('....O..\\|..')
            print('...\\|/..|..')
            print('....|...|..')
            print('........|..')
            print('........|..')
            print('._________.')
            print('.|.......|.')
        elif numFails == 5:
            print('..-------..')
            print('......\\.|..')
            print('....O..\\|..')
            print('...\\|/..|..')
            print('....|...|..')
            print('.../.\\..|..')
            print('........|..')
            print('._________.')
            print('.|.......|.')
        print()
